# Generated by Django 4.2.6 on 2023-10-15 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
